include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
    always_declare_return_types: true
    prefer_final_locals: true
    unnecessary_this: true
    annotate_overrides: true
    avoid_init_to_null: true
